// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mivzcpssqsxhoitcxaiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pdnpjcHNzcXN4aG9pdGN4YWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2Mzg4NjYsImV4cCI6MjA0OTIxNDg2Nn0.DK0OjuamUQPP8u2BcLOpuurse4tK8g247JOfshVnH9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);